services:

  main:
    build:
      context: local/
      args:
        USER: ${UID:-1000}
        GROUP: ${UID:-1000}
    container_name: main
    command: tail -f /dev/null
    volumes:
      - ./:/opt/www
    ports:
      - 9501:9501
    environment:
      - APP_ENV=dev
      - SCAN_CACHEABLE=false
    depends_on:
      - mysql
      - redis

  redis:
    image: bitnami/redis:latest
    environment:
      - REDIS_PASSWORD=my_password
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'

  mysql:
    image: 'bitnami/mysql:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=my_user
      - MYSQL_PASSWORD=my_password
      - MYSQL_DATABASE=my_database
    ports:
      - '3306:3306'
    volumes:
      - 'mysql_data:/bitnami/mysql/data'

volumes:
  redis_data:
  mysql_data:

